
CREATE TABLE wdbc(
	id_number INTEGER,
	diagnosis VARCHAR (10),
	radius_mean 	 	 NUMERIC, 
	texture_mean		 NUMERIC,
	perimeter_mean		 NUMERIC,
	area_mean		 NUMERIC,
	smoothness_mean  	 NUMERIC, 
	compactness_mean	 NUMERIC,
	concavity_mean	 	 NUMERIC, 
	concave_points_mean 	 NUMERIC,
	symmetry_mean	   	 NUMERIC,
	fractal_dimension_mean 	 NUMERIC, 
	radius_SE	 	 NUMERIC, 
	texture_SE		 NUMERIC,
	perimeter_SE		 NUMERIC,
	area_SE			 NUMERIC,
	smoothness_SE	 	 NUMERIC, 
	compactness_SE		 NUMERIC,
	concavity_SE	 	 NUMERIC, 
	concave_points_SE 	 NUMERIC,
	symmetry_SE	   	 NUMERIC,
	fractal_dimension_SE 	 NUMERIC, 
	radius_worst	 	 NUMERIC, 
	texture_worst		 NUMERIC,
	perimeter_worst		 NUMERIC,
	area_worst		 NUMERIC,
	smoothness_worst  	 NUMERIC, 
	compactness_worst	 NUMERIC,
	concavity_worst	 	 NUMERIC, 
	concave_points_worst 	 NUMERIC,
	symmetry_worst	   	 NUMERIC,
	fractal_dimension_worst  NUMERIC
);
